import Link from "next/link";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { currentUser } from "@/lib/session";

export default async function ProfilePage() {
  const user = await currentUser(); if (!user) redirect("/auth");
  const [listings, buyCount, saleCount] = await Promise.all([db.listing.findMany({ where: { sellerId: user.id }, include: { game: true, gameVariant: true }, orderBy: { createdAt: "desc" }, take: 30 }), db.order.count({ where: { buyerId: user.id } }), db.order.count({ where: { sellerId: user.id } })]);
  return <div className="container"><div className="profile-head"><span className="profile-avatar">{user.name.slice(0, 1)}</span><div><p className="eyebrow">ACCOUNT CENTER</p><h1>{user.name}</h1><p>{user.email} · 注册于 {new Date(user.createdAt).toLocaleDateString("zh-MY")}</p></div><Link className="button secondary" href="/verify">管理 Email 验证</Link></div><div className="profile-metrics"><div><span>Email</span><strong className={user.emailVerified ? "good-text" : "coral-text"}>{user.emailVerified ? "已验证" : "待验证"}</strong></div><div><span>购买订单</span><strong>{buyCount}</strong></div><div><span>销售订单</span><strong>{saleCount}</strong></div><div><span>风险标记</span><strong>{user.riskFlags}</strong></div></div>{user.banned && <div className="notice coral">此账号已被暂停交易，请联系平台管理员。</div>}<div className="two-column" style={{ marginTop: 18 }}><section className="panel"><div className="panel-title"><div><h2>我的商品</h2><p>商品审核状态和管理员备注。</p></div><Link className="button compact" href="/sell">发布商品</Link></div>{listings.length ? listings.map((item) => <div className="data-row" key={item.id}><div><strong>{item.title}</strong><p className="muted">{item.game.name} · {item.gameVariant?.label || "通用"} · RM {item.price.toFixed(2)}</p></div><span className={item.status === "ACTIVE" ? "status good" : item.status === "REJECTED" ? "status bad" : "status warn"}>{item.status}</span></div>) : <div className="empty">还没有发布商品。</div>}</section><aside className="panel"><h2>账号安全</h2><div className="data-row"><span>主要验证方式</span><strong>{user.emailVerified ? "EMAIL" : "未验证"}</strong></div><div className="data-row"><span>实名认证</span><span className={user.realNameVerified ? "status good" : "status"}>{user.realNameVerified ? "已完成" : "后续开放"}</span></div><div className="data-row"><span>手机号</span><strong>{user.phone || "未填写"}</strong></div><p className="muted">当前只有 Email OTP 用于开启交易权限。高风险操作的额外验证将在正式接入服务商后开放。</p></aside></div></div>;
}
