"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/client-api";

type Props = { orderId: string; status: string; isBuyer: boolean; isSeller: boolean; messages: { id: string; body: string; riskFlag: boolean; createdAt: string; sender: { name: string } }[] };

export function OrderActions({ orderId, status, isBuyer, isSeller, messages }: Props) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [showDispute, setShowDispute] = useState(false);
  async function post(url: string, body: unknown) { setBusy(true); setError(""); try { await api(url, { method: "POST", body: JSON.stringify(body) }); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失败"); } finally { setBusy(false); } }
  async function proof(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); let fileKey: string | undefined; const file = data.get("file") as File; if (file?.size) { if (file.size > 10 * 1024 * 1024) { setError("凭证文件不可超过 10 MB"); return; } try { const signed = await api<{ uploadUrl: string; fileKey: string }>("/api/uploads/payment-proof", { method: "POST", body: JSON.stringify({ contentType: file.type }) }); const upload = await fetch(signed.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!upload.ok) throw new Error("凭证文件上传失败"); fileKey = signed.fileKey; } catch (cause) { setError(cause instanceof Error ? cause.message : "上传失败"); return; } } await post(`/api/orders/${orderId}/payment-proof`, { method: data.get("method"), reference: data.get("reference"), fileKey }); }
  async function action(event: FormEvent<HTMLFormElement>, name: string) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await post(`/api/orders/${orderId}/action`, { action: name, ...data }); }
  async function message(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const body = new FormData(form).get("body"); await post(`/api/orders/${orderId}/messages`, { body }); form.reset(); }
  const closed = ["COMPLETED", "REFUNDED", "CANCELLED"].includes(status);
  return <div className="trade-workspace">
    {isBuyer && ["PAYMENT_REVIEW", "PAYMENT_REJECTED"].includes(status) && <form className="panel action-card" onSubmit={proof}><div className="action-card-head"><span className="step-icon">1</span><div><h3>提交付款凭证</h3><p>转账完成后填写参考编号，管理员确认入账后才会通知卖家。</p></div></div><div className="form-grid"><div className="field"><label>付款方式</label><select className="select" name="method"><option>DuitNow QR</option><option>FPX Online Banking</option><option>Bank Transfer</option><option>TNG eWallet</option><option>GrabPay</option><option>Boost</option></select></div><div className="field"><label>付款参考编号</label><input className="input" name="reference" required minLength={3} placeholder="银行或钱包参考编号"/></div><div className="field wide"><label>凭证图片或 PDF</label><label className="upload-zone"><input type="file" name="file" accept="image/jpeg,image/png,image/webp,application/pdf"/><strong>选择付款凭证</strong><span>JPG、PNG、WebP 或 PDF，最大 10 MB</span></label></div></div><div className="action-footer"><button className="button secondary" type="button" disabled={busy} onClick={() => post(`/api/orders/${orderId}/action`, { action: "CANCEL" })}>取消订单</button><button className="button primary" disabled={busy}>上传并提交审核</button></div></form>}
    {isSeller && status === "AWAITING_DELIVERY" && <form className="panel action-card" onSubmit={(event) => action(event, "DELIVER")}><div className="action-card-head"><span className="step-icon">2</span><div><h3>在平台内交付商品</h3><p>交付资料只会显示给当前买家和管理员。</p></div></div><textarea className="textarea" name="deliverySecret" required minLength={1} placeholder="账号资料、兑换码、改绑步骤或其他交付说明..."/><div className="notice"><strong>交付检查：</strong>确认区服、账号资料和售后范围与商品说明一致。</div><div className="action-footer"><span/><button className="button primary" disabled={busy}>提交交付</button></div></form>}
    {isBuyer && status === "DELIVERED" && <div className="panel action-card"><div className="action-card-head"><span className="step-icon">3</span><div><h3>验收交付内容</h3><p>请先登录或检查商品。确认后平台会把订单金额计入卖家余额。</p></div></div><div className="accept-actions"><button className="button primary" disabled={busy} onClick={() => post(`/api/orders/${orderId}/action`, { action: "ACCEPT" })}>确认验收并放款</button><button className="button danger" type="button" onClick={() => setShowDispute(!showDispute)}>交付有问题</button></div>{showDispute && <form className="dispute-form" onSubmit={(event) => action(event, "DISPUTE")}><label>申诉原因与证据说明</label><textarea className="textarea" name="reason" required minLength={10} placeholder="说明无法登录、商品不符或其他问题，并在聊天中补充证据。"/><button className="button danger" disabled={busy}>提交管理员处理</button></form>}</div>}

    <section className="panel chat-room"><div className="panel-title"><div><h3>订单聊天与证据</h3><p>请勿发送私人收款方式、外部联系账号或要求离开平台交易。</p></div><span className="status good">自动风险提醒</span></div><div className="message-list">{messages.length ? messages.map((item) => <article className={item.riskFlag ? "message risk-message" : "message"} key={item.id}><span className="avatar">{item.sender.name.slice(0, 1)}</span><div><div><strong>{item.sender.name}</strong><small>{new Date(item.createdAt).toLocaleString("zh-MY")}</small></div><p>{item.body}</p>{item.riskFlag && <span className="status bad">检测到私下交易关键词</span>}</div></article>) : <div className="empty compact-empty">还没有聊天记录。所有沟通都会按时间保留在订单内。</div>}</div>{!closed && <form className="message-compose" onSubmit={message}><textarea name="body" required maxLength={2000} placeholder="输入消息或描述证据..."/><button className="button primary" disabled={busy}>发送</button></form>}</section>
    {error && <p className="form-error">{error}</p>}
  </div>;
}
