import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { db } from "@/lib/db";
import { currentUser } from "@/lib/session";
import { walletBalance } from "@/lib/wallet";

export default async function AdminUserPage({ params }: { params: Promise<{ id: string }> }) {
  const admin = await currentUser(); if (!admin) redirect("/auth"); if (admin.role !== "ADMIN") redirect("/");
  const { id } = await params;
  const [user, balance] = await Promise.all([db.user.findUnique({ where: { id }, include: { sellerProfile: true, listings: { include: { game: true, gameVariant: true }, orderBy: { createdAt: "desc" }, take: 30 }, purchases: { include: { listing: true }, orderBy: { createdAt: "desc" }, take: 30 }, sales: { include: { listing: true }, orderBy: { createdAt: "desc" }, take: 30 }, withdrawals: { orderBy: { createdAt: "desc" }, take: 30 }, otpChallenges: { where: { channel: "EMAIL" }, orderBy: { createdAt: "desc" }, take: 30 } } }), walletBalance(id)]);
  if (!user) notFound();
  return <div className="container"><div className="profile-head"><span className="profile-avatar">{user.name.slice(0, 1)}</span><div><p className="eyebrow">CUSTOMER RECORD · {user.id.slice(-8)}</p><h1>{user.name}</h1><p>{user.email}{user.phone ? ` · ${user.phone}` : ""} · 注册 {new Date(user.createdAt).toLocaleString("zh-MY")}</p></div><Link className="button secondary" href="/admin">返回后台</Link></div><div className="admin-grid" style={{ marginTop: 14 }}><div className="metric"><strong>RM {balance.toFixed(2)}</strong><span>钱包余额</span></div><div className="metric"><strong>{user.purchases.length}</strong><span>购买订单</span></div><div className="metric"><strong>{user.sales.length}</strong><span>销售订单</span></div><div className="metric"><strong>{user.riskFlags}</strong><span>风险标记</span></div></div><div className="two-column"><section className="stack"><div className="panel"><div className="panel-title"><h2>验证与状态</h2><span className={user.banned ? "status bad" : "status good"}>{user.banned ? "已封禁" : "正常"}</span></div><div className="data-row"><span>Email OTP</span><span className={user.emailVerified ? "status good" : "status warn"}>{user.emailVerified ? "已验证" : "未验证"}</span></div><div className="data-row"><span>手机号</span><strong>{user.phone || "未填写"}</strong></div><div className="data-row"><span>实名认证</span><span className={user.realNameVerified ? "status good" : "status"}>{user.realNameVerified ? "已完成" : "未完成"}</span></div><div className="data-row"><span>主要验证</span><strong>{user.emailVerified ? "EMAIL" : "无"}</strong></div></div><div className="panel"><h2>商品记录</h2>{user.listings.length ? user.listings.map((row) => <div className="data-row" key={row.id}><div><strong>{row.title}</strong><p className="muted">{row.game.name} · {row.gameVariant?.label || "通用"} · RM {row.price.toFixed(2)}</p></div><span className="status">{row.status}</span></div>) : <p className="muted">无商品记录</p>}</div><div className="panel"><h2>提款记录</h2>{user.withdrawals.length ? user.withdrawals.map((row) => <div className="data-row" key={row.id}><div><strong>RM {row.amount.toFixed(2)}</strong><p className="muted">{row.account}</p></div><span className="status">{row.status}</span></div>) : <p className="muted">无提款记录</p>}</div></section><aside className="panel"><h2>Email OTP 记录</h2>{user.otpChallenges.length ? user.otpChallenges.map((row) => <div className="data-row" key={row.id}><div><strong>{row.purpose}</strong><p className="muted">{row.destination}<br/>{new Date(row.createdAt).toLocaleString("zh-MY")}</p></div><div><span className={row.verifiedAt ? "status good" : row.deliveryStatus === "FAILED" ? "status bad" : "status warn"}>{row.verifiedAt ? "VERIFIED" : row.deliveryStatus}</span><p className="muted">尝试 {row.attempts}/{row.maxAttempts}</p></div></div>) : <p className="muted">没有 Email OTP 记录</p>}</aside></div></div>;
}
